import { useEffect, useRef, useState, type FormEvent } from "react";
import { NavLink, useSearchParams } from "react-router-dom";
import { ArrowUpRight, Building2, Check, LoaderCircle, Plus, Search, X } from "lucide-react";
import { api, type Business } from "./api";
import type { Dataset, CollectedListing } from "./intelligence-data";
import "./business-picker.css";
import ReputationDashboard from "./ReputationDashboard";
import { listingIdentity } from "./evidence-insights";

interface Result { dataset:Dataset; listing:CollectedListing }
interface SearchJob {id:string;status:"running"|"completed"|"failed";dataset?:Dataset;error?:string;cached?:boolean}
async function request<T>(path:string,body?:unknown):Promise<T>{const response=await fetch(path,body?{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}:undefined);const result=await response.json();if(!response.ok)throw new Error(result.error??"Request failed.");return result;}
export function BusinessPicker({close,added,purpose="owned"}:{close:()=>void;added:()=>void;purpose?:"owned"|"competitor"}) {
  const [destination,setDestination]=useState(purpose);const [savedName,setSavedName]=useState("");
  const [mode,setMode]=useState<"placeId"|"search">("placeId");const [query,setQuery]=useState("");const [datasets,setDatasets]=useState<Dataset[]>([]);const [selected,setSelected]=useState<Result|null>(null);
  const [job,setJob]=useState<SearchJob|null>(null),[error,setError]=useState(""),[saving,setSaving]=useState(false),[starting,setStarting]=useState(false),[available,setAvailable]=useState(false),[loaded,setLoaded]=useState(false);
  const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{dialog.current?.showModal();let active=true;Promise.all([request<Dataset[]>("/api/intelligence/imports"),request<{available:boolean}>("/api/business-search/status")]).then(([data,status])=>{if(active){setDatasets(rows=>[...rows,...data.filter(dataset=>!rows.some(row=>row.id===dataset.id))]);setAvailable(status.available);setLoaded(true)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false;};},[]);
  useEffect(()=>{
    if(job?.status!=="running")return;let active=true;let timer:ReturnType<typeof setTimeout>;
    const poll=async()=>{try{const result=await request<SearchJob>(`/api/business-search/${job.id}`);if(!active)return;setJob(result);if(result.status==="completed"&&result.dataset){setDatasets(rows=>[result.dataset!,...rows.filter(d=>d.id!==result.dataset!.id)]);setSelected(null);}if(result.status==="failed")setError(result.error??"Search failed.");if(result.status==="running")timer=setTimeout(()=>void poll(),2000);}catch(e){if(active){setError(e instanceof Error?e.message:"Search status unavailable.");timer=setTimeout(()=>void poll(),4000);}}};
    timer=setTimeout(()=>void poll(),1000);return()=>{active=false;clearTimeout(timer);};
  },[job?.id,job?.status]);
  const seen=new Set<string>();
  const results:Result[]=[];
  for(const dataset of datasets){if(dataset.source==="illustrative")continue;for(const listing of dataset.listings){const key=listing.placeId??listing.cid;if(!key||seen.has(key))continue;seen.add(key);const match=[listing.name,listing.address,listing.placeId,listing.mapsUrl].join(" ").toLowerCase();if(job?.status==="completed"&&job.dataset?.id===dataset.id||!query.trim()||query.trim().toLowerCase().split(/\s+/).every(word=>match.includes(word)))results.push({dataset,listing});}}
  async function search(event:FormEvent){event.preventDefault();setStarting(true);setSelected(null);setError("");try{const result=await request<SearchJob>("/api/business-search",mode==="placeId"?{placeId:query.trim()}:{query:query.trim()});setJob(result);if(result.dataset)setDatasets(rows=>[result.dataset!,...rows.filter(d=>d.id!==result.dataset!.id)]);}catch(e){setError(e instanceof Error?e.message:"Search could not start.");}finally{setStarting(false);}}
  async function add(){if(!selected)return;setSaving(true);setError("");try{await request(destination==="competitor"?"/api/competitor-workspace/select":"/api/businesses/select",{datasetId:selected.dataset.id,listingId:selected.listing.id});added();if(destination==="competitor")setSavedName(selected.listing.name);else close();}catch(e){setError(e instanceof Error?e.message:"Could not add business.");}finally{setSaving(false);}}
  const searching=starting||job?.status==="running";
  return <dialog ref={dialog} className="business-picker" onCancel={e=>{if(saving)e.preventDefault();else close();}} aria-labelledby="business-picker-title"><div className="picker-heading"><div><span>{destination==="competitor"?"FIND A COMPETITOR":"FIND YOUR BUSINESS"}</span><h2 id="business-picker-title">Search and select a location</h2></div><button className="icon-button" aria-label="Close business search" onClick={close} disabled={saving}><X size={19}/></button></div>
    {savedName?<div className="notice" role="status">{savedName} saved as a competitor. <NavLink to="/competitors" onClick={close}>Open competitor watchlist</NavLink></div>:null}
    {purpose==="owned"&&<label className="picker-destination">Add this listing as<select aria-label="Add this listing as" value={destination} disabled={saving||searching} onChange={e=>{setDestination(e.target.value as "owned"|"competitor");setSavedName("");setError("")}}><option value="owned">My business — owned location</option><option value="competitor">Competitor — monitored business</option></select></label>}
    <div className="picker-method" role="group" aria-label="Find business method"><button type="button" aria-pressed={mode==="placeId"} disabled={saving||searching} onClick={()=>{setMode("placeId");setQuery("");setJob(null);setSelected(null);setError("")}}>Use Place ID</button><button type="button" aria-pressed={mode==="search"} disabled={saving||searching} onClick={()=>{setMode("search");setQuery("");setJob(null);setSelected(null);setError("")}}>Search by name or link</button></div>
    <p className="picker-intro">{mode==="placeId"?<>Open <a href="https://developers.google.com/maps/documentation/javascript/examples/places-placeid-finder" target="_blank" rel="noreferrer">Google’s Place ID finder <ArrowUpRight size={12}/></a>, find your business, then copy its Place ID here. This targets one listing and skips the broad name search.</>:"Enter the exact business name and city, or paste a Google Maps link. Broad terms such as ‘dental’ collect multiple listings and take longer."} Check the address before selecting.</p>
    <form onSubmit={search} className="picker-search"><label htmlFor="business-search">{mode==="placeId"?"Google Place ID":"Business name and city or Google Maps link"}</label><div><Search size={18}/><input id="business-search" autoFocus placeholder={mode==="placeId"?"Paste a Google Place ID":"Enter a business name and city or paste a Maps link"} minLength={mode==="placeId"?10:3} maxLength={mode==="placeId"?300:2000} value={query} disabled={saving||searching} onChange={e=>{setQuery(e.target.value);setSelected(null);setJob(null);}}/><button className="button" disabled={(mode==="search"&&!available)||query.trim().length<(mode==="placeId"?10:3)||searching||saving}>{searching?<><LoaderCircle size={16}/>Loading…</>:mode==="placeId"?"Load business":"Search Google Maps"}</button></div></form>
    {error&&<div className="error-box" role="alert">{error}</div>}
    {searching&&<div className="picker-progress" role="status"><LoaderCircle size={17}/><div><strong>{mode==="placeId"?"Loading this Google Maps listing":"Searching public Google Maps listings"}</strong><p>{mode==="placeId"?"The Place ID skips name discovery. Loading public details still requires a browser visit; this may take up to three minutes.":"The collector opens and reads matching listings. An exact name and city returns fewer results and is faster."}</p></div></div>}
    {job?.cached&&<p className="picker-hint" role="status">Exact Place ID matched saved details. No new collection was needed; check the collection date below.</p>}{loaded&&!available&&<p className="picker-hint">Live search is unavailable until the local collector is set up. Previously collected listings remain selectable.</p>}
    <div className="picker-results-heading"><strong>{job?.status==="completed"?"Search results":"Previously collected matches"}</strong><span>{results.length} {results.length===1?"listing":"listings"}</span></div>
    <div className="picker-results" role="group" aria-label="Business search results">{results.slice(0,30).map(result=>{const active=selected?.dataset.id===result.dataset.id&&selected.listing.id===result.listing.id;return <button type="button" className={`picker-result ${active?"selected":""}`} key={`${result.dataset.id}:${result.listing.id}`} aria-pressed={active} onClick={()=>setSelected(result)} disabled={saving}><span className="picker-result-icon">{active?<Check size={20}/>:<Building2 size={20}/>}</span><span className="picker-result-main"><strong>{result.listing.name}</strong><span>{result.listing.address??"Address not collected"}</span><small>{result.listing.category??"Category not collected"} · {result.dataset.collectedAt?`Collected ${new Date(result.dataset.collectedAt).toLocaleDateString()}`:"Collection date unknown"}</small></span><span className="picker-rating"><strong>{result.listing.rating??"—"}</strong><small>{result.listing.reviewCount??"—"} reviews</small></span></button>})}{!results.length&&!searching&&<div className="picker-empty"><Search size={25}/><p>{loaded?(mode==="placeId"?"Paste your Place ID and click Load business.":"No saved matches. Enter a business name and city, then search Google Maps."):"Loading saved listings…"}</p></div>}</div>
    <div className="picker-footer"><p>{selected?<><strong>{selected.listing.name}</strong> selected. {destination==="competitor"?"This saves it to your competitor watchlist and uses one monitored-business slot.":"This uses one monitored-business slot. Google management access is optional and requires a separate authorized connection."}</>:"Select a result to add your business. No manual address entry is needed."}</p><button className="button" onClick={()=>void add()} disabled={!selected||saving||searching}>{saving?"Adding…":destination==="competitor"?"Add selected competitor":"Add selected business"}</button></div>
  </dialog>;
}
export default function BusinessesWorkspace(){
  const [params]=useSearchParams();const [items,setItems]=useState<Business[]>([]),[open,setOpen]=useState(params.get("add")==="1"),[error,setError]=useState("");
  const [datasets,setDatasets]=useState<Dataset[]>([]),[selected,setSelected]=useState("");
  const load=async()=>{try{const [businesses,imports]=await Promise.all([api.businesses(),request<Dataset[]>("/api/intelligence/imports")]);setItems(businesses);setDatasets(imports);setSelected(current=>businesses.some(b=>b.id===current)?current:businesses.find(b=>b.publicListingKey)?.id??businesses[0]?.id??"");setError("");}catch(e){setError((e as Error).message);}};useEffect(()=>{void load()},[]);
  const business=items.find(b=>b.id===selected);
  const dataset=[...datasets].filter(d=>d.source!=="illustrative").sort((a,b)=>Date.parse(b.collectedAt??b.importedAt)-Date.parse(a.collectedAt??a.importedAt)).find(d=>d.listings.some(l=>listingIdentity(l)===business?.publicListingKey));
  const listing=dataset?.listings.find(l=>listingIdentity(l)===business?.publicListingKey);
  return <><div className="page-head"><div><h1>Your businesses</h1><p>Add your Google business, review its collected evidence and watch for changes.</p></div><button className="button" onClick={()=>setOpen(true)}><Plus size={17}/>Add business</button></div>{error&&<div className="error-box" role="alert">{error}</div>}{items.length>0&&<label className="rep-dashboard-picker">Protect a business<select aria-label="View your business dashboard" value={selected} onChange={e=>setSelected(e.target.value)}>{items.map(b=><option key={b.id} value={b.id}>{b.name}{b.publicListingKey?"":" (preview / manual)"}</option>)}</select></label>}{dataset&&listing?<ReputationDashboard key={dataset.id+listing.id} owned listing={listing} dataset={dataset} datasets={datasets} onCollected={()=>void load()}/>:business&&<p className="notice">This record has no collected Google evidence. Use Add business to find and select its public listing.</p>}<details className="rep-managed-list"><summary>Manage your businesses · {items.length}</summary><div className="owned-listings">{items.map(b=><article key={b.id}><div className="owned-symbol"><Building2 size={23}/></div><div><span className="owned-source">{b.publicListingKey?"Public listing selected":"Manual / preview record"}</span><h2>{b.name}</h2><p>{b.address}</p><div className="owned-facts"><span>{b.category}</span><span>{b.rating||"—"} ★ · {b.reviewCount.toLocaleString()} reported reviews</span></div>{b.publicListingKey&&<NavLink to={`/platforms?business=${encodeURIComponent(b.publicListingKey)}`}>Facebook &amp; Trustpilot profiles <ArrowUpRight size={15}/></NavLink>}{b.sourceDatasetId?<NavLink to={`/evidence?scope=owned&dataset=${b.sourceDatasetId}`}>View collected evidence <ArrowUpRight size={15}/></NavLink>:<span className="owned-note">Select this business through search to attach public listing evidence.</span>}</div></article>)}</div></details>{!items.length&&<p className="picker-hint">Add a business to start collecting its public profile.</p>}{open&&<BusinessPicker close={()=>setOpen(false)} added={()=>{void load();window.dispatchEvent(new Event("axiocred:refresh"));}}/>}</>;
}
