import {useEffect,useState,type FormEvent} from "react";
import {NavLink} from "react-router-dom";
import "./collection-workspace.css";

interface Job {id:string;query:string;queries?:string[];status:string;startedAt:string;datasetId?:string;listingCount:number;partial?:boolean;warning?:string;error?:string}
interface Runtime {available:boolean;proxyConfigured:boolean;maxQueries:number;maxCells:number;maxListings:number;tuning?:{concurrency:number;browserPool:number;pagesPerBrowser:number}}
async function request<T>(url:string,body?:unknown):Promise<T>{const res=await fetch(url,body?{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}:undefined);const data=await res.json();if(!res.ok)throw new Error(data.error??"Request failed.");return data;}
export default function CollectionWorkspace(){
  const [visibleJobs,setVisibleJobs]=useState(10);
  const [jobs,setJobs]=useState<Job[]>([]),[runtime,setRuntime]=useState<Runtime|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
  const [mode,setMode]=useState("details"),[area,setArea]=useState("none");
  async function refresh(){try{const [rows,state]=await Promise.all([request<Job[]>("/api/collections"),request<Runtime>("/api/collections/runtime")]);setJobs(rows);setRuntime(state);setError("");}catch(e){setError((e as Error).message);}}
  useEffect(()=>{void refresh();},[]);
  const running=jobs.some(job=>job.status==="running");
  useEffect(()=>{if(!running)return;const timer=setInterval(()=>void refresh(),3000);return()=>clearInterval(timer);},[running]);
  async function start(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);setBusy(true);setError("");try{
    const number=(key:string)=>Number(data.get(key));
    const options={mode,language:String(data.get("language")),depth:number("depth"),maxListings:number("maxListings"),zoom:number("zoom"),emails:mode==="details"&&data.has("emails"),extendedReviews:mode==="details"&&data.has("extendedReviews"),
      ...(area==="center"?{geo:{latitude:number("latitude"),longitude:number("longitude"),radius:number("radius")}}:{}),
      ...(area==="grid"?{grid:{south:number("south"),west:number("west"),north:number("north"),east:number("east"),cellKm:number("cellKm")}}:{})};
    await request("/api/collections",{queries:String(data.get("queries")).split(/\r?\n/).map(q=>q.trim()).filter(Boolean),options});setNotice("Native collection started. You can leave this page and return to inspect the result.");await refresh();
  }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function cancel(id:string){try{const result=await request<{message:string}>(`/api/collections/${id}/cancel`,{});setNotice(result.message);await refresh();}catch(e){setError((e as Error).message);}}
  async function retry(id:string){try{await request(`/api/collections/${id}/retry`,{});setNotice("New collection started with the saved options.");await refresh();}catch(e){setError((e as Error).message);}}
  return <div className="collection-workspace"><div className="page-head"><div><h1>Collect business evidence</h1><p>Find businesses, capture their public details, then choose which ones to protect or monitor.</p></div><NavLink className="button secondary" to="/evidence">Open review library</NavLink></div>
    <ol className="collection-steps"><li>Define searches and area</li><li>Collect with the native scraper</li><li>Inspect evidence and select businesses</li></ol>
    <section className="collection-runtime"><strong>{runtime?(runtime.available?"Native collector ready":"Native runtime unavailable"):"Checking native runtime…"}</strong><p>One active local run · up to 10 queries · 100 query/cell combinations · up to 1,000 saved listings. Collection stops after 20 minutes and may be partial.</p><small>Worker tuning: {runtime?.tuning?.concurrency??1} concurrent tasks, {runtime?.tuning?.browserPool??1} browser contexts, {runtime?.tuning?.pagesPerBrowser??1} pages per context. Proxy file: {runtime?.proxyConfigured?"configured on server":"not configured"}. Outscraper is only an exact-business fallback; batch and grid jobs never call it. Paid fallback has a separate operator-controlled budget.</small></section>
    {error&&<p role="alert" className="error-box">{error}</p>}{notice&&<p role="status">{notice}</p>}
    <form onSubmit={start} className="collection-form"><h2>New collection</h2><label>Searches, one per line<textarea name="queries" required rows={4} placeholder={'Dentists in Indirapuram\nDental clinics in Ghaziabad'} maxLength={20000}/></label><small>Use business names and cities, categories, or full Google Maps links. A bare Place ID belongs in the business picker.</small>
      <div className="collection-fields"><label>Collection mode<select value={mode} onChange={e=>{setMode(e.target.value);if(e.target.value==="fast")setArea("center");}}><option value="details">Detailed business evidence</option><option value="fast">Fast listing discovery · reduced fields</option></select></label><label>Search language<input name="language" defaultValue="en" required pattern="[a-z]{2,3}(-[A-Za-z]{2,4})?"/></label><label>Search depth<input name="depth" type="number" min={1} max={50} defaultValue={10} required/></label><label>Maximum saved listings<input name="maxListings" type="number" min={1} max={1000} defaultValue={200} required/></label><label>Map zoom<input name="zoom" type="number" min={1} max={21} defaultValue={15} required/></label><label>Search area<select value={area} onChange={e=>setArea(e.target.value)}><option value="none" disabled={mode==="fast"}>Use the location in the query</option><option value="center">Center coordinates</option><option value="grid" disabled={mode==="fast"}>Grid across a bounding box</option></select></label></div>
      {area==="center"&&<fieldset><legend>Center coordinates</legend><div className="collection-fields"><label>Latitude<input name="latitude" type="number" min={-90} max={90} step="any" required/></label><label>Longitude<input name="longitude" type="number" min={-180} max={180} step="any" required/></label>{mode==="fast"?<label>Radius in meters<input name="radius" type="number" min={1} max={100000} defaultValue={10000} required/></label>:<input type="hidden" name="radius" value="10000"/>}</div><small>{mode==="fast"?"Radius filters fast discovery results.":"Coordinates bias the search; detailed collection does not enforce a radius."}</small></fieldset>}
      {area==="grid"&&<fieldset><legend>Grid boundaries</legend><div className="collection-fields">{[["south","South latitude",-85,85],["west","West longitude",-180,180],["north","North latitude",-85,85],["east","East longitude",-180,180]].map(([name,label,min,max])=><label key={name}>{label}<input name={String(name)} type="number" min={min} max={max} step="any" required/></label>)}<label>Cell size in kilometers<input name="cellKm" type="number" min={0.1} max={50} step="any" defaultValue={1} required/></label></div><small>Overlapping results are deduplicated by listing identity. A grid is broader discovery, not a local-pack rank check.</small></fieldset>}
      {mode==="details"&&<div className="collection-toggles"><label><input type="checkbox" name="emails"/>Discover emails from business websites</label><label><input type="checkbox" name="extendedReviews"/>Collect extended review history</label><small>Website emails are unverified. Extended history takes longer and cannot guarantee all reviews.</small></div>}
      <button className="button" disabled={busy||running||!runtime?.available}>{busy?"Starting…":running?"A collection is running":"Start native collection"}</button>
    </form>
    <section className="collection-history"><div className="page-head"><h2>Recent collection jobs</h2><button className="button secondary" onClick={()=>void refresh()}>Refresh jobs</button></div>{!jobs.length&&<p>No collection jobs yet. Start with a business name and city above.</p>}{jobs.slice(0,visibleJobs).map(job=><article key={job.id}><div><strong>{job.queries?.join(" · ")??job.query}</strong><small>{new Date(job.startedAt).toLocaleString()} · {job.status}{job.partial?" · partial run":""} · {job.listingCount} listings saved</small>{job.warning&&<p>{job.warning}</p>}{job.error&&<p>{job.error}</p>}</div><div>{job.datasetId&&<NavLink className="button secondary" to={`/evidence?dataset=${job.datasetId}`}>Inspect collected evidence</NavLink>}{job.status!=="running"&&<button className="button secondary" disabled={running||!runtime?.available} onClick={()=>void retry(job.id)}>Run again</button>}{job.status==="running"&&<button className="button secondary" onClick={()=>void cancel(job.id)}>Cancel collection</button>}</div></article>)}{jobs.length>visibleJobs&&<button className="button secondary" onClick={()=>setVisibleJobs(value=>value+10)}>Show more jobs</button>}<p>Job history survives a local restart. Interrupted runs require a new collection; this is not a distributed worker queue.</p></section>
    <div className="collection-next"><NavLink to="/businesses">Select a business to protect →</NavLink><NavLink to="/competitors">Add a competitor to monitor →</NavLink><NavLink to="/enrichment">Inspect discovered contacts →</NavLink></div>
  </div>;
}
