import {useEffect,useRef,useState} from "react";
import {Link,useLocation} from "react-router-dom";
import {ArrowRight,ArrowUpRight,Check,ChevronDown,Eye,FileCheck2,Layers3,Menu,Search,ShieldCheck,X} from "lucide-react";
import {marketingPlans} from "./plan-catalog";
import "./landing.css";

const features=[
  {name:"Watch your market",icon:Eye,title:"Your business. Their business. Your perspective.",text:"Build a watchlist from Google listings, then inspect the public evidence. You don’t need to own a business to understand its reputation.",rows:["Choose an exact Google listing","Keep competitors in a dedicated watchlist","Compare saved ratings and review counts"],view:"watch"},
  {name:"Inspect the evidence",icon:Search,title:"Look beyond the star rating.",text:"Read the reviews actually collected, compare available snapshots and follow each record back to its source.",rows:["Collected and reported totals stay separate","See original text and available owner replies","Track changes across saved snapshots"],view:"evidence"},
  {name:"Prepare your next step",icon:FileCheck2,title:"A clearer case starts with clearer evidence.",text:"Organize a review locator and supporting notes. Review the facts yourself before using the platform’s reporting tools.",rows:["Expandable report kits","Downloadable review locators","You verify the reason and submit"],view:"report"},
  {name:"Connect the context",icon:Layers3,title:"Three platforms. One business slot.",text:"Link Facebook and Trustpilot to a Google business. Each source keeps its own reviews, ratings and access status.",rows:["Same-business confirmation","Separate source histories","Public collection previews, with honest limits"],view:"platforms"}
];
const comparisons=[
  ["Monitored businesses","1 audit","1","5","Unlimited¹"],
  ["Checks for changes²","One time","Twice a day","Four times a day","Custom"],
  ["Own or competitor business","Either","Either","Any mix","Any mix"],
  ["Google listing evidence","Planned audit","On demand","On demand","Planned scale"],
  ["Facebook & Trustpilot links","—","Included","Included","Included"],
  ["Platform review collection","—","Limited preview","Limited preview","Access dependent"],
  ["Review locators & report kits","—","Included","Included","Included"],
  ["Google AI review assessment","—","Requires setup","Requires setup","Requires setup"],
  ["Enterprise API & webhooks","—","—","—","Planned"]
];
const faqs=[
  ["Do I need to own a business?","No. You can select any available Google business listing and add it to your watchlist. Google Business Profile management access is a separate, optional connection for businesses you are authorized to manage."],
  ["What counts as one monitored business?","One business anchored to its Google listing. Linking that same business’s Facebook Page and Trustpilot profile does not use another slot. Business includes one; Growth includes five in any mix."],
  ["Can I choose how often it checks?","The frequency comes with your plan: twice a day on Business, four times a day on Growth. There is no interval to configure. Automatic checking is still being built; the local preview collects on demand."],
  ["Does it collect every review on every platform?","No. Google collection can return a partial sample. Facebook and Trustpilot public collection is experimental and can be blocked. The dashboard separates reported review totals from the texts actually collected."],
  ["Can AI prove a review is fake?","No. An assessment can highlight patterns that deserve attention; it cannot establish someone’s intent or prove an interaction did not happen. Google AI assessment requires configuration, and other-platform analysis is planned."],
  ["Will Axio-CRED report reviews for me?","No. Report kits help you locate reviews and organize evidence. You check the applicable platform rules and make the final submission. A low rating alone is not a reason to report a review."],
  ["Is this ready for a paid production account?","This is a local product preview. Production account isolation, live billing verification, automatic checks and reliable platform connectors remain release requirements. The preview does not take a payment when you explore it."]
];

function Preview({view="watch"}:{view?:string}){return <div className="lp-product" aria-label="Illustrative product preview"><div className="lp-product-top"><span className="lp-mini-brand">AX</span><strong>Reputation workspace</strong><span>Illustrative preview</span></div><div className="lp-product-body"><div className="lp-product-rail"><Eye/><Search/><Layers3/><FileCheck2/></div><div className="lp-product-main"><div className="lp-product-heading"><div><span>YOUR EVIDENCE, CONNECTED</span><h3>{view==="report"?"Review report kit":view==="platforms"?"Business platforms":view==="evidence"?"Review evidence":"Market watchlist"}</h3></div><span className="lp-dot-label">Preview</span></div>{view==="report"?<><div className="lp-mini-review"><span>REVIEW LOCATOR</span><h4>Start with the original source.</h4><p>Business · Author · Date · Review text</p><div className="lp-paper-line"/><div className="lp-paper-line short"/></div><ol className="lp-preview-list"><li>Locate the original review</li><li>Verify the policy reason</li><li>Submit through the platform</li></ol><span className="lp-mini-note"><ShieldCheck size={15}/>The final decision stays with you.</span></>:view==="platforms"?<div className="lp-platform-preview">{["Google","Facebook","Trustpilot"].map((p,i)=><div key={p}><span>{p[0]}</span><strong>{p}</strong><small>{i===0?"Business reference":"Linked profile · separate evidence"}</small></div>)}<p>One business · one paid slot</p></div>:<><div className="lp-preview-metrics"><div><span>Reported reviews</span><strong>240</strong></div><div><span>Collected sample</span><strong>24<span> reviews</span></strong></div></div>{view==="evidence"?<div className="lp-mini-review"><span>ORIGINAL REVIEW TEXT</span><h4>Evidence you can read and verify.</h4><p>Available text, author details and collection time stay together.</p><div className="lp-paper-line"/><div className="lp-paper-line short"/></div>:<div className="lp-mini-table"><div><span>Business</span><span>Evidence</span></div>{["Your selected business","A nearby competitor","Another market listing"].map((s,i)=><div key={s}><span><i>{i+1}</i>{s}</span><span>{i===2?"Link saved":"Partial sample"}</span></div>)}</div>}<div className="lp-preview-bottom"><span><FileCheck2 size={15}/>Sources attached to each review</span><ArrowUpRight size={16}/></div></>}</div></div><div className="lp-preview-caption">Fictional example · not live business data</div></div>;}

export default function LandingPage(){
  const location=useLocation();const [menu,setMenu]=useState(false),[active,setActive]=useState(0),[playing,setPlaying]=useState(false),[reduced,setReduced]=useState(false);const tabs=useRef<(HTMLButtonElement|null)[]>([]);
  const previewUrl=`/overview${location.search}`;
  useEffect(()=>{const media=window.matchMedia?.("(prefers-reduced-motion: reduce)");if(!media)return;const change=()=>setReduced(media.matches);change();media.addEventListener("change",change);return()=>media.removeEventListener("change",change);},[]);
  useEffect(()=>{if(!playing||reduced)return;const timer=setInterval(()=>setActive(n=>(n+1)%features.length),4000);return()=>clearInterval(timer);},[playing,reduced]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==="Escape")setMenu(false);};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[]);
  useEffect(()=>{document.title="Axio-CRED — Understand your business reputation";if(location.hash||location.pathname==="/pricing"){requestAnimationFrame(()=>document.getElementById(location.hash.slice(1)||"pricing")?.scrollIntoView());}return()=>{document.title="Axio-CRED";};},[location.hash,location.pathname]);
  const CTA=({secondary=false,children="Explore the preview"}:{secondary?:boolean;children?:React.ReactNode})=><Link className={`lp-button ${secondary?"lp-secondary":""}`} to={previewUrl}>{children}<ArrowRight size={17}/></Link>;
  const selected=features[active];
  return <div className="lp"><a className="lp-skip" href="#main">Skip to content</a><div className="lp-announcement">Meet your next reputation workspace. <a href="#availability">Explore what’s ready <ArrowRight size={13}/></a></div>
    <header className="lp-nav"><div className="lp-wrap lp-nav-inner"><Link to="/" className="lp-brand"><span>AX</span>Axio-CRED</Link><nav className={menu?"lp-nav-links open":"lp-nav-links"} id="marketing-navigation" aria-label="Website navigation">{[["Features","features"],["How it works","how-it-works"],["Pricing","pricing"],["FAQ","faq"]].map(([name,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{name}</a>)}</nav><div className="lp-nav-actions"><Link to="/login">Log in</Link><CTA/></div><button className="lp-menu" aria-label={menu?"Close menu":"Open menu"} aria-expanded={menu} aria-controls="marketing-navigation" onClick={()=>setMenu(v=>!v)}>{menu?<X/>:<Menu/>}</button></div></header>
    <main id="main" className="lp-main"><section className="lp-hero lp-wrap"><div className="lp-hero-copy"><span className="lp-eyebrow"><span/> REPUTATION, WITH THE EVIDENCE</span><h1>See the changes.<br/><em>Know your<br/>next move.</em></h1><p>A clearer view of your business and your competitors. Bring listings, review evidence and your next steps into one workspace.</p><div className="lp-hero-actions"><CTA/><a className="lp-text-link" href="#features">Take a closer look <ArrowUpRight size={18}/></a></div><small>Local preview · no payment to explore · no business ownership required</small></div><div className="lp-hero-visual"><div className="lp-orbit"/><Preview/><div className="lp-floating"><ShieldCheck/><div><strong>Evidence before conclusions.</strong><span>Original sources. Clear limitations. Your decision.</span></div></div></div></section>
    <section className="lp-sources lp-wrap" aria-label="Business platforms"><p>ONE BUSINESS. A WIDER PICTURE.</p><div><span>Google <small>Public listing collection</small></span><span>facebook <small>Profile linking · limited collection</small></span><span>★ Trustpilot <small>Profile linking · limited collection</small></span></div><p>Platform names identify data sources, not endorsements or partnerships.</p></section>
    <section className="lp-section lp-wrap"><span className="lp-eyebrow">LESS GUESSWORK</span><h2>A star rating is only<br/>the beginning of the story.</h2><div className="lp-benefits">{[[Eye,"Keep a closer watch","Give each business a place in your watchlist. Separate the competition you care about from unrelated listings."],[Search,"See the whole context","Read the evidence you actually have. Know when a review sample is partial or a source cannot be accessed."],[FileCheck2,"Make a considered move","Prepare the review locator and supporting notes before deciding whether there is a reason to report."]].map(([Icon,title,body])=>{const I=Icon as typeof Eye;return <article key={String(title)}><I/><h3>{String(title)}</h3><p>{String(body)}</p></article>;})}</div></section>
    <section className="lp-section lp-feature-section" id="features"><div className="lp-wrap"><span className="lp-eyebrow">INSIDE THE WORKSPACE</span><h2>From scattered reviews<br/>to a clearer picture.</h2><div className="lp-feature-layout"><div className="lp-feature-tabs" role="tablist" aria-label="Product features" aria-orientation="vertical">{features.map((f,i)=><button id={`feature-tab-${i}`} ref={el=>{tabs.current[i]=el;}} key={f.name} role="tab" aria-selected={active===i} aria-controls="feature-panel" tabIndex={active===i?0:-1} onClick={()=>{setActive(i);setPlaying(false);}} onKeyDown={e=>{if(["ArrowDown","ArrowUp","Home","End"].includes(e.key)){e.preventDefault();const next=e.key==="Home"?0:e.key==="End"?features.length-1:(i+(e.key==="ArrowDown"?1:features.length-1))%features.length;setActive(next);setPlaying(false);tabs.current[next]?.focus();}}}><f.icon size={22}/><span>{f.name}</span><ArrowUpRight size={16}/></button>)}</div><div id="feature-panel" role="tabpanel" aria-labelledby={`feature-tab-${active}`} className="lp-feature-content"><h3>{selected.title}</h3><p>{selected.text}</p><ul>{selected.rows.map(row=><li key={row}><Check size={17}/>{row}</li>)}</ul><Preview view={selected.view}/></div></div><div className="lp-feature-footer"><CTA/><button className="lp-text-link" disabled={reduced} onClick={()=>setPlaying(v=>!v)}>{playing?"Pause feature tour":"Play feature tour"}</button></div></div></section>
    <section className="lp-section lp-wrap" id="how-it-works"><span className="lp-eyebrow">A SIMPLE START</span><h2>Find it. Inspect it. Follow through.</h2><div className="lp-steps">{[["Choose a business","Find its Google listing or enter a Place ID. Your business or a competitor: either works."],["Gather the context","Collect a public snapshot. Link the matching Facebook and Trustpilot profiles when available."],["Review your next step","Inspect the sources, record your observations and prepare a report locator when the evidence supports it."]].map(([title,text],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="lp-plan-stats lp-wrap" aria-label="Plan facts"><div><strong>1 slot</strong><span>One business across three platforms</span></div><div><strong>2× / day</strong><span>Business plan checks · planned</span></div><div><strong>4× / day</strong><span>Growth plan checks · planned</span></div></section>
    <section className="lp-section lp-wrap lp-principles"><div><span className="lp-eyebrow">BUILT AROUND WHAT YOU CAN VERIFY</span><h2>Clear evidence.<br/>Clear boundaries.</h2></div><div><article><span>01</span><h3>A source behind the record.</h3><p>Keep available review text, collection time and source links together.</p></article><article><span>02</span><h3>Missing data stays missing.</h3><p>A blocked source or a partial sample is visible. It is never presented as complete coverage.</p></article><article><span>03</span><h3>You make the final call.</h3><p>A pattern is a reason to investigate. It does not automatically make a review fake.</p></article></div></section>
    <section className="lp-section lp-wrap lp-deep"><div><span className="lp-eyebrow">THE NEXT STEP IS PART OF THE WORK</span><h2>Don’t lose the context<br/>when it’s time to act.</h2><p>Expandable report kits bring the review locator, original wording and your supporting notes together. File through the platform after checking its rules.</p><CTA secondary/></div><Preview view="report"/></section>
    <section className="lp-section lp-wrap" id="availability"><span className="lp-eyebrow">WHAT YOU CAN USE TODAY</span><h2>Know what’s connected.<br/>Know what’s still coming.</h2><div className="lp-availability">{[["Google","On-demand collection","Find a listing and inspect its collected review sample."],["Facebook + Trustpilot","Limited preview","Link matching profiles. Public collection can be blocked."],["OpenAI assessment","Setup required","Google review triage requires a configured API key. Other-platform analysis is planned."],["PayPal + Enterprise API","Setup / development","Live billing verification and enterprise API delivery remain pending."]].map(([name,status,desc])=><article key={name}><span>{status}</span><h3>{name}</h3><p>{desc}</p></article>)}</div></section>
    <section className="lp-pricing" id="pricing"><div className="lp-wrap"><span className="lp-eyebrow">SIMPLE PLANS. NO INTERVAL SETTINGS.</span><h2>Choose your scope.<br/>The checking frequency is included.</h2><p className="lp-pricing-intro">Your own businesses, competitors, or a mix. Google, Facebook and Trustpilot profiles for the same business share one slot.</p><div className="lp-price-grid">{marketingPlans.map(plan=><article key={plan.name} className={plan.name==="Growth"?"lp-price featured":"lp-price"}>{plan.name==="Growth"&&<span className="lp-price-badge">FOR A WIDER VIEW</span>}<h3>{plan.name}</h3><p>{plan.description}</p><strong>{plan.price}{["Business","Growth"].includes(plan.name)&&<small>/month</small>}</strong><b>{plan.businesses}</b><span className="lp-frequency">{plan.frequency}{["Business","Growth"].includes(plan.name)&&" for changes²"}</span><ul>{plan.features.map(f=><li key={f}><Check size={16}/>{f}</li>)}</ul><CTA/><small className="lp-price-note">{plan.note}</small></article>)}</div><p className="lp-pricing-note">Local preview: paid automatic checks and the free audit flow are not active yet. No payment is required to explore.</p><details className="lp-comparison" open={location.pathname==="/pricing"}><summary>Compare every plan <ChevronDown size={20}/></summary><div className="lp-table-scroll" tabIndex={0} aria-label="Plan feature comparison"><table><caption>Plan scope and current availability</caption><thead><tr>{["Feature","Free audit","Business","Growth","Enterprise"].map(s=><th scope="col" key={s}>{s}</th>)}</tr></thead><tbody>{comparisons.map(([feature,...cells])=><tr key={feature}><th scope="row">{feature}</th>{cells.map((c,i)=><td key={i}>{c}</td>)}</tr>)}</tbody></table></div><p>¹ Enterprise capacity, storage and delivery require further implementation and an agreed service scope. ² Twice- and four-times-daily checks are the approved plan design; the scheduler is not running yet.</p></details></div></section>
    <section className="lp-section lp-wrap lp-faq" id="faq"><div><span className="lp-eyebrow">BEFORE YOU START</span><h2>Fair questions.<br/>Straight answers.</h2></div><div>{faqs.map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={18}/></summary><p>{a}</p></details>)}</div></section>
    <section className="lp-final"><div className="lp-wrap"><span className="lp-eyebrow">PUT THE EVIDENCE IN FRONT OF YOU</span><h2>Your market is worth<br/>a closer look.</h2><CTA/><p>Explore the local preview. No payment required.</p></div></section>
    </main><footer className="lp-footer lp-wrap"><div><Link className="lp-brand" to="/"><span>AX</span>Axio-CRED</Link><p>A clearer view of business reputation.</p></div><div><strong>Explore</strong><a href="#features">Features</a><a href="#pricing">Plan comparison</a><Link to={previewUrl}>Dashboard preview</Link></div><div><strong>Before you start</strong><a href="#availability">Current availability</a><a href="#faq">Questions & answers</a><Link to="/login">Log in</Link></div><div className="lp-footer-bottom"><span>© {new Date().getFullYear()} Axio-CRED</span><span>Local preview · production privacy and terms review pending</span></div></footer><div className="lp-mobile-cta"><CTA/></div></div>;
}
