import type {CollectedListing} from "./intelligence-data";
import "./collection-workspace.css";
function Link({url,label}:{url:string|null|undefined;label:string}){if(!url||!/^https?:\/\//i.test(url))return null;return <a href={url} target="_blank" rel="noreferrer">{label}</a>;}
export default function ListingFacts({listing:l}:{listing:CollectedListing}){
  const facts=[["Place ID",l.placeId],["CID",l.cid],["Source input ID",l.inputId],["Google data ID",l.dataId],["Categories",l.categories?.join(", ")||l.category],["Phone",l.phone],["Website",l.website],["Public status",l.status],["Coordinates",l.latitude!==null&&l.longitude!==null?`${l.latitude}, ${l.longitude}`:null],["Plus code",l.plusCode],["Timezone",l.timezone],["Price range",l.priceRange],["Description",l.description],["Accepted card networks",l.creditCards?.join(", ")],["Structured address",Object.entries(l.structuredAddress??{}).filter(([,value])=>value).map(([key,value])=>`${key}: ${value}`).join("; ")],["Hours",Object.entries(l.hours).map(([day,hours])=>`${day}: ${hours.join(", ")}`).join("; ")]];
  return <div className="listing-facts-rich"><p>Public source observations. Missing data means not collected; a listed owner is not verified account ownership.</p><dl>{facts.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||"Not collected"}</dd></div>)}</dl>
    <h3>Source and service links</h3><ul>{[[l.mapsUrl,"Google Maps"],[l.reviewsUrl,"Reviews"],[l.streetViewUrl,"Street View"],[l.owner?.url,l.owner?.name?`Listed owner: ${l.owner.name}`:"Listed owner"],[l.menu?.url,"Menu"],...(l.reservations??[]).map(row=>[row.url,`Reservations · ${row.source??"source"}`]),...(l.orderOnline??[]).map(row=>[row.url,`Order online · ${row.source??"source"}`])].filter(([url])=>url).map(([url,label],index)=><li key={index}><Link url={url} label={label!}/></li>)}</ul>
    <h3>Business attributes</h3>{(l.attributes??[]).length?(l.attributes??[]).map((group,index)=><details key={index}><summary>{group.name??group.id??"Attributes"}</summary><ul>{group.options.map((option,i)=><li key={i}>{option.name}: {option.enabled?"Listed as available":"Listed as unavailable"}{option.values?.length?` · ${option.values.join(", ")}`:""}</li>)}</ul></details>):<p>Not collected.</p>}
    <h3>Popular times</h3><p>Relative popularity reported by Google, not visitor counts or live occupancy.</p>{Object.keys(l.popularTimes??{}).length?Object.entries(l.popularTimes??{}).map(([day,hours])=><details key={day}><summary>{day}</summary>{Object.entries(hours).sort(([a],[b])=>Number(a)-Number(b)).map(([hour,value])=><div className="popular-hour" key={hour}><span>{hour.padStart(2,"0")}:00</span><progress max={100} value={value}/><span>{value} / 100</span></div>)}</details>):<p>Not collected.</p>}
    <details><summary>Collected media links · {l.images.length}</summary><p>Media links can expire. No image ownership or manipulation is inferred.</p><ul>{l.images.map((image,index)=><li key={index}><Link url={image.url} label={image.title??`Photo ${index+1}`}/></li>)}</ul></details>
  </div>;
}
