import {afterEach,describe,it,expect,vi} from "vitest";
import {render,screen,cleanup,fireEvent} from "@testing-library/react";
import {MemoryRouter} from "react-router-dom";
import MissionWorkspace from "./MissionWorkspace";
import WorkflowShell from "./WorkflowShell";
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
function setup(){HTMLDialogElement.prototype.showModal=function(){this.setAttribute("open","");};vi.stubGlobal("fetch",vi.fn(async(path:string)=>({ok:true,json:async()=>path.includes("competitor-workspace")?{targets:[],baselineKey:null}:path.includes("overview")?{plan:"Growth",locationsUsed:0,locationsLimit:5}:path.includes("collector")?{available:true}:[]})));}
describe("goal-based workspace",()=>{
 it("provides independent protect and competitor paths without forcing business ownership",async()=>{setup();render(<MemoryRouter><MissionWorkspace/></MemoryRouter>);expect(await screen.findByRole("button",{name:"Add my business"})).toBeInTheDocument();expect(screen.getByRole("button",{name:"Monitor my first competitor"})).toBeInTheDocument();expect(screen.getByText(/without adding your own business/)).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Monitor my first competitor"}));expect(await screen.findByRole("dialog")).toBeInTheDocument();});
 it("exposes all requested channels without claiming that email or WhatsApp is connected",async()=>{setup();render(<MemoryRouter initialEntries={["/alerts?scope=competitor"]}><MissionWorkspace alerts/></MemoryRouter>);expect(await screen.findByRole("combobox",{name:"Alert business scope"})).toHaveValue("competitor");expect(screen.getByText("Email alerts")).toBeInTheDocument();expect(screen.getByText("WhatsApp alerts")).toBeInTheDocument();expect(screen.getByText(/provider and recipients not connected/)).toBeInTheDocument();expect(screen.getByText(/Meta connection and recipients not configured/)).toBeInTheDocument();expect(screen.queryByText("SMS alerts")).not.toBeInTheDocument();expect(screen.getByText(/No matching changes/)).toBeInTheDocument();});
 it("groups sidebar actions and lets keyboard users close mobile navigation",async()=>{setup();render(<MemoryRouter><WorkflowShell><div>Content</div></WorkflowShell></MemoryRouter>);expect(screen.getByRole("link",{name:"Protect my business"})).toHaveAttribute("href","/businesses");expect(screen.getByRole("link",{name:"Monitor competitors"})).toHaveAttribute("href","/competitors");fireEvent.click(screen.getByRole("button",{name:"Open workspace menu"}));expect(screen.getByRole("button",{name:"Close workspace menu"})).toHaveAttribute("aria-expanded","true");fireEvent.keyDown(window,{key:"Escape"});expect(screen.getByRole("button",{name:"Open workspace menu"})).toHaveAttribute("aria-expanded","false");});
});
