import BusinessNextSteps from "./BusinessNextSteps";
import {useEffect,useState} from "react";
import {NavLink,useSearchParams} from "react-router-dom";
import {ArrowRight,ArrowUpRight,Bell,Check,ChevronRight,FileCheck2,Plus,Radar,RefreshCw,ShieldCheck} from "lucide-react";
import {BusinessPicker} from "./BusinessesWorkspace";
import {detectChanges,monitoredEntities,signalUrl,type MonitoringData,type ChangeSignal} from "./monitoring-activity";
import {planFrequency} from "./plan-catalog";
import "./mission.css";

function useMonitoring(){const [data,setData]=useState<MonitoringData|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);try{const results=await Promise.all(["businesses","competitor-workspace","intelligence/imports","overview"].map(async route=>{const response=await fetch(`/api/${route}`);if(!response.ok)throw new Error("Could not load your monitoring workspace. Retry to see current evidence.");return response.json();}));setData({businesses:results[0],watch:results[1],datasets:results[2],overview:results[3]});setError("");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void load();},[]);return {data,error,busy,load};}
const kindLabel={low_review:"Low-rated review",new_review:"Newly observed review",missing_reviews:"Reviews not seen",count_decrease:"Review count decrease",burst:"Review activity",profile:"Profile change",rating:"Rating drop"};
function SignalCard({signal}:{signal:ChangeSignal}){return <article className="mission-signal"><div className={`mission-signal-icon ${signal.type}`}><Bell size={19}/></div><div><div className="mission-signal-meta"><span>{signal.entity.competitor?"Competitor":"Your business"} · {signal.entity.name}</span><span>{new Date(signal.at).toLocaleString()}</span></div><h3>{signal.title}</h3><p>{signal.detail}</p><small>Compared {new Date(signal.from).toLocaleString()} → {new Date(signal.at).toLocaleString()}</small><NavLink to={signalUrl(signal)}>Review evidence <ArrowRight size={15}/></NavLink></div></article>;}

export default function MissionWorkspace({alerts=false}:{alerts?:boolean}){
 const {data,error,busy,load}=useMonitoring();const [picker,setPicker]=useState<"owned"|"competitor"|null>(null),[params,setParams]=useSearchParams();const scope=params.get("scope")??"all",type=params.get("type")??"all";
 const entities=data?monitoredEntities(data):[],signals=data?detectChanges(entities,data.datasets):[];
 const owned=entities.filter(e=>e.owned),competitors=entities.filter(e=>e.competitor),comparable=entities.filter(e=>e.snapshots>=2);
 const filtered=signals.filter(s=>(scope==="all"||(scope==="owned"?s.entity.owned:s.entity.competitor))&&(type==="all"||s.type===type));
 const allChecks=entities.flatMap(e=>e.latest?.dataset.collectedAt?[e.latest.dataset.collectedAt]:[]).sort((a,b)=>Date.parse(b)-Date.parse(a));
 return <div className="mission-page"><div className="mission-heading"><div><span className="mission-eyebrow">{alerts?"REVIEW WHAT NEEDS ATTENTION":"YOUR REPUTATION WORKSPACE"}</span><h1>{alerts?"Alerts & changes":entities.length?"Your reputation, at a glance":"What would you like to do today?"}</h1><p>{alerts?"Changes observed in collected evidence, with a clear next step.":"Protect your business, follow competitors and act on the evidence."}</p></div><button className="button secondary" onClick={()=>void load()} disabled={busy}><RefreshCw size={16}/>{busy?"Refreshing…":"Refresh workspace"}</button></div>
 {error&&<div className="error-box" role="alert">{error}</div>}
 {!data&&!error?<div className="mission-empty">Loading your businesses and saved evidence…</div>:data&&<>
 {!alerts&&entities.length>0&&<BusinessNextSteps entities={entities}/>}
 {!alerts&&<><details className="mission-goals" open={entities.length===0}><summary>{entities.length?"Add a business or choose a monitoring goal":"Choose your first goal"}</summary><div className="mission-paths"><section className="mission-path protect"><div className="mission-path-icon"><ShieldCheck size={27}/></div><span>01 / PROTECT</span><h2>Protect my business</h2><p>Watch your listing details and low-rated reviews. Review changes before deciding how to respond.</p><ol><li><Check size={14}/>Add your Google business</li><li>Check reviews and profile changes</li><li>Prepare a response or report</li></ol>{owned.length?<><NavLink className="button" to="/businesses">Review my {owned.length===1?"business":"businesses"}<ArrowRight size={15}/></NavLink><button className="text-button" onClick={()=>setPicker("owned")}>Add another business <Plus size={14}/></button></>:<button className="button" onClick={()=>setPicker("owned")}><Plus size={16}/>Add my business</button>}</section><section className="mission-path monitor"><div className="mission-path-icon"><Radar size={27}/></div><span>02 / MONITOR</span><h2>Monitor competitors</h2><p>Follow low-rated reviews, rating drops and unusual review activity. Build a report when the evidence supports it.</p><ol><li><Check size={14}/>Choose a competitor on Google</li><li>Inspect new observations and bursts</li><li>Verify evidence before reporting</li></ol>{competitors.length?<><NavLink className="button" to="/competitors">Open competitor watchlist <ArrowRight size={15}/></NavLink><button className="text-button" onClick={()=>setPicker("competitor")}>Add a competitor <Plus size={14}/></button></>:<button className="button" onClick={()=>setPicker("competitor")}><Plus size={16}/>Monitor my first competitor</button>}</section></div><p className="mission-no-owner">You can monitor competitors without adding your own business. A business with linked Facebook and Trustpilot profiles still uses one slot.</p></details></>}
 <div className="mission-status"><div><strong>{data.overview.locationsUsed} / {data.overview.locationsLimit??"unlimited"}</strong><span>business slots used</span></div><div><strong>{signals.length}</strong><span>observations in latest comparisons</span></div><div><strong>{comparable.length} / {entities.length}</strong><span>businesses with comparable snapshots</span></div><div><strong>{allChecks.length?new Date(allChecks[0]).toLocaleDateString(undefined,{day:"numeric",month:"short"}):"Not checked"}</strong><span>latest saved collection</span></div></div>
 {data.businesses.some(b=>!b.publicListingKey)&&<p className="mission-footnote">The allowance includes {data.businesses.filter(b=>!b.publicListingKey).length} manual or preview business records. <NavLink to="/businesses">Review business records</NavLink>.</p>}
 <div className="mission-delivery"><Bell size={21}/><div><strong>Review changes from saved checks here.</strong><p>{planFrequency(data.overview.plan)} is your plan cadence. Enable automatic checks beside the collection controls. Local schedules require this PC and API to stay running; email and WhatsApp delivery are not connected.</p></div><NavLink to={alerts?"/settings":"/alerts"}>{alerts?"Connection settings":"View alerts inbox"} <ArrowUpRight size={15}/></NavLink></div>
 {alerts?<><section className="alert-channel-grid" aria-label="Alert delivery channels"><article><Bell size={20}/><strong>In-app inbox</strong><span>Available from saved comparisons</span></article><article><Bell size={20}/><strong>Email alerts</strong><span>Planned · provider and recipients not connected</span></article><article><Bell size={20}/><strong>WhatsApp alerts</strong><span>Planned · Meta connection and recipients not configured</span></article></section><div className="mission-filter"><label>Businesses<select aria-label="Alert business scope" value={scope} onChange={e=>setParams({scope:e.target.value,type})}><option value="all">All monitored businesses</option><option value="owned">My businesses</option><option value="competitor">Competitors</option></select></label><label>Observation type<select aria-label="Alert type" value={type} onChange={e=>setParams({scope,type:e.target.value})}><option value="all">All changes</option>{Object.entries(kindLabel).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><span>{filtered.length} observations</span></div><div className="mission-rule-note">Newly observed reviews include all ratings; 1–2 stars are highlighted. Reviews not seen again are unconfirmed absences, not verified removals. Review activity jump: at least 10 additional reported reviews across two checks no more than 24 hours apart. These are investigation rules, not proof of manipulation.</div></>:<div className="mission-section-heading"><div><h2>Observed changes</h2><p>Compare snapshots, then verify the underlying reviews.</p></div><NavLink to="/alerts">Open alerts inbox <ArrowRight size={15}/></NavLink></div>}
 {(alerts?filtered:signals.slice(0,3)).length?(alerts?filtered:signals.slice(0,3)).map(s=><SignalCard key={s.id} signal={s}/>):<section className="mission-empty"><Bell size={28}/><h2>{alerts?"No matching changes in available comparisons":comparable.length?"No new observations to review":"Build your monitoring baseline"}</h2><p>{comparable.length?"No changes matched these rules in the latest available comparisons. Partial samples and missing collections can hide activity.":"A first snapshot records the starting point. Collect again later to compare reviews, ratings and profile details."}</p><div><NavLink className="button secondary" to={owned.length?"/businesses":"/competitors"}>Open monitored businesses <ArrowRight size={15}/></NavLink><NavLink className="text-button" to="/evidence">Browse collected reviews</NavLink></div></section>}
 {!alerts&&<section className="mission-portfolio"><div className="mission-section-heading"><div><h2>Continue with a business</h2><p>Open its evidence or connect another platform.</p></div><NavLink to="/reports"><FileCheck2 size={16}/> Report queue</NavLink></div>{entities.length?entities.map(e=><article key={e.key}><div className="mission-entity-icon">{e.owned?<ShieldCheck size={20}/>:<Radar size={20}/>}</div><div><strong>{e.name}</strong><small>{e.owned?"Your business":"Competitor"} · {e.latest?`${e.latest.listing.reviews.length} collected / ${e.latest.listing.reviewCount??"unknown"} reported reviews`:"Collect and link its Google evidence to continue"}</small></div>{e.latest?<NavLink to={`/evidence?dataset=${encodeURIComponent(e.latest.dataset.id)}&listing=${encodeURIComponent(e.latest.listing.id)}&scope=${e.owned?"owned":"competitor"}`}>Review business <ChevronRight size={16}/></NavLink>:<NavLink to={e.owned?"/businesses":"/competitors"}>Finish setup <ChevronRight size={16}/></NavLink>}</article>):<p>Add a business above to start your workspace.</p>}</section>}
 <p className="mission-footnote">Observations are calculated when this page loads from the latest saved dataset window. They are not a complete or continuously delivered notification history.</p>
 </>}{picker&&<BusinessPicker purpose={picker} close={()=>setPicker(null)} added={()=>{setPicker(null);void load();window.dispatchEvent(new Event("axiocred:refresh"));}}/>}</div>;
}
