import {describe,it,expect} from "vitest";
import {detectChanges,monitoredEntities,type MonitoringData} from "./monitoring-activity";
import {demoDataset,type Dataset} from "./intelligence-data";
const older:Dataset={...demoDataset,id:"before",source:"scraper_import",collectedAt:"2026-09-06T00:00:00Z",listings:[{...demoDataset.listings[0],placeId:"one",rating:4.8,reviewCount:100,reviews:[{...demoDataset.listings[0].reviews[0],id:"existing",rating:1}]}]};
const newer:Dataset={...older,id:"after",collectedAt:"2026-09-06T12:00:00Z",listings:[{...older.listings[0],rating:4.5,reviewCount:115,phone:"changed",reviews:[...older.listings[0].reviews,{...older.listings[0].reviews[0],id:"new-to-sample",rating:2}]}]};
function data(datasets:Dataset[]):MonitoringData{return {businesses:[],watch:{baselineKey:null,targets:[{id:"target",name:"Competitor",listingKey:"place:one",mapsUrl:null}]},datasets,overview:{} as any};}
describe("saved-snapshot alert rules",()=>{
 it("does not create new-review alerts solely because the collector changed",()=>{const switched:Dataset={...newer,collection:{provider:"outscraper"}};const input=data([older,switched]);const signals=detectChanges(monitoredEntities(input),input.datasets);expect(signals.some(s=>s.type==="low_review")).toBe(false);expect(signals.some(s=>s.type==="burst")).toBe(true);});
 it("requires two timed snapshots and never treats first collection as a new-review event",()=>{for(const datasets of [[older],[{...older,collectedAt:null},newer],[{...older,source:"illustrative" as const},newer]])expect(detectChanges(monitoredEntities(data(datasets)),datasets)).toEqual([]);});
 it("detects review observations, rating drop, count jump and public profile edits with source references",()=>{const input=data([older,newer]);const signals=detectChanges(monitoredEntities(input),input.datasets);expect(signals.map(s=>s.type)).toEqual(["low_review","burst","rating","profile"]);expect(signals.filter(s=>s.type==="low_review")).toHaveLength(1);expect(signals[0].reviewId).toBe("new-to-sample");expect(signals[0].detail).toContain("posting time is not established");expect(signals[0].datasetId).toBe("after");});
 it("does not call a slow count increase a burst or repeatedly flag reviews seen in older samples",()=>{const middle={...older,id:"middle",collectedAt:"2026-09-07T00:00:00Z",listings:[{...older.listings[0],reviews:[]}]};const last={...newer,collectedAt:"2026-09-09T00:00:00Z",listings:[{...newer.listings[0],reviews:older.listings[0].reviews}]};const input=data([older,middle,last]);const signals=detectChanges(monitoredEntities(input),input.datasets);expect(signals.some(s=>s.type==="burst")).toBe(false);expect(signals.some(s=>s.type==="low_review")).toBe(false);});
 it("excludes unrelated imports and merges the same owned/competitor identity",()=>{const input=data([older,newer]);input.businesses=[{publicListingKey:"place:one",name:"Owned"} as any];const entities=monitoredEntities(input);expect(entities).toHaveLength(1);expect(entities[0].owned&&entities[0].competitor).toBe(true);input.watch.targets=[];input.businesses=[];expect(monitoredEntities(input)).toEqual([]);});
});
