import {useEffect,useState,type FormEvent} from "react";
import {useSearchParams} from "react-router-dom";
import {ArrowUpRight,Link2,RefreshCw} from "lucide-react";
import "./platforms.css";

type Platform="facebook"|"trustpilot";
interface Review {id:string;author:string|null;text:string;rating:number|null;postedAt:string|null}
interface Snapshot {id:string;collectedAt:string;sourceUrl:string;name:string|null;rating:number|null;reviewCount:number|null;reviews:Review[];digest:string}
interface Profile {id:string;entityKey:string;platform:Platform;url:string;lastAttemptAt:string|null;error:string|null;snapshots:Snapshot[]}
const label=(p:Platform)=>p==="facebook"?"Facebook":"Trustpilot";
async function api<T>(path:string,method="GET",body?:unknown):Promise<T>{const r=await fetch(path,{method,...(method!=="GET"?{headers:{"Content-Type":"application/json"},body:JSON.stringify(body??{})}:{})});const data=await r.json();if(!r.ok)throw new Error(data.error??"Platform request failed.");return data;}

export default function PlatformWorkspace(){
  const [params,setParams]=useSearchParams();const selected=params.get("business")??"";
  const [entities,setEntities]=useState<{key:string;name:string}[]>([]),[profiles,setProfiles]=useState<Profile[]>([]);
  const [error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
  async function load(){
    try{
      const [owned,watch,data]=await Promise.all([api<{name:string;publicListingKey?:string}[]>("/api/businesses"),api<{baselineKey:string|null;targets:{name:string;listingKey:string|null}[]}>("/api/competitor-workspace"),api<{profiles:Profile[]}>("/api/platform-profiles")]);
      const unique=new Map<string,string>();for(const b of owned)if(b.publicListingKey&&/^(place:|cid:)/.test(b.publicListingKey))unique.set(b.publicListingKey,b.name);for(const t of watch.targets)if(t.listingKey&&/^(place:|cid:)/.test(t.listingKey))unique.set(t.listingKey,t.name);
      setEntities([...unique].map(([key,name])=>({key,name})));setProfiles(data.profiles);setError("");
    }catch(e){setError((e as Error).message);}finally{setLoading(false);}
  }
  useEffect(()=>{void load();},[]);
  const entity=entities.find(e=>e.key===selected);
  async function save(platform:Platform,event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);setError("");setNotice("");try{const profile=await api<Profile>("/api/platform-profiles","PUT",{entityKey:selected,platform,url:form.get("url"),confirmedSameBusiness:form.get("same")==="on"});setProfiles(old=>[...old.filter(p=>p.id!==profile.id),profile]);setNotice(`${label(platform)} profile linked to ${entity?.name}. No extra business slot used.`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function collect(profile:Profile){setBusy(true);setError("");setNotice("");try{const result=await api<Profile>(`/api/platform-profiles/${profile.id}/collect`,"POST");setProfiles(old=>old.map(p=>p.id===result.id?result:p));setNotice(result.error?`${label(profile.platform)} collection could not complete. See its access status below.`:`${label(profile.platform)} public snapshot saved. Coverage is partial.`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function unlink(profile:Profile){setBusy(true);setError("");try{await api(`/api/platform-profiles/${profile.id}`,"DELETE");setProfiles(old=>old.filter(p=>p.id!==profile.id));setNotice("Platform profile and its preview snapshots removed. The Google business is retained.");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <div className="platform-page"><div className="page-head"><div><h1>Business platforms</h1><p>One business. Google, Facebook and Trustpilot. One monitored slot.</p></div></div>
    <section className="panel platform-selector"><label>Google business<select aria-label="Google business" value={selected} disabled={busy||loading} onChange={e=>{setParams(e.target.value?{business:e.target.value}:{});setNotice("");}}><option value="">Select a saved Google business</option>{entities.map(e=><option key={e.key} value={e.key}>{e.name}</option>)}</select></label><p>Add a business from its Google listing first, then link its matching platform profiles. Business ownership is not required. Links are confirmed by you, not independently verified.</p></section>
    {error&&<div className="error-box" role="alert">{error}</div>}{notice&&<div className="notice" role="status">{notice}</div>}
    {!entity?<p className="platform-empty">{loading?"Loading saved businesses…":"Choose a Google business above. Pending Maps links must be collected and selected before adding other platforms."}</p>:<>
      <div className="platform-summary"><strong>{entity.name}</strong><span>Google is the business reference · Facebook and Trustpilot use separate review records</span></div>
      <div className="platform-grid">{(["facebook","trustpilot"] as const).map(platform=>{const profile=profiles.find(p=>p.entityKey===selected&&p.platform===platform),snapshot=profile?.snapshots[0];return <section className="panel platform-card" key={selected+platform}><header><div className={`platform-symbol ${platform}`} aria-hidden="true">{platform==="facebook"?"f":"★"}</div><div><h2>{label(platform)}</h2><span>{profile?snapshot?"Partial snapshot available":"Profile linked · no collected data":"Not linked"}</span></div></header>
        <form onSubmit={e=>void save(platform,e)}><label>{label(platform)} business profile URL<input name="url" type="url" required defaultValue={profile?.url??""} key={profile?.url??"empty"} placeholder={platform==="facebook"?"https://www.facebook.com/yourbusiness":"https://www.trustpilot.com/review/example.com"}/></label><label className="platform-confirm"><input type="checkbox" name="same" required/>I checked that this profile represents {entity.name}. {platform==="trustpilot"?"A company-wide Trustpilot profile may cover several locations.":"Use the business Page, not a personal account."}</label><button className="button secondary" disabled={busy}><Link2 size={15}/>{profile?"Update profile link":"Link profile"}</button></form>
        {profile&&<><div className="platform-actions"><a className="button secondary" href={profile.url} target="_blank" rel="noreferrer">Open {label(platform)} <ArrowUpRight size={15}/></a><button className="button" disabled={busy} onClick={()=>void collect(profile)}><RefreshCw size={15}/>{busy?"Please wait…":"Try public collection"}</button></div><p className="platform-note">Public-page preview · one page · up to 100 review texts · no scheduled collection. Login-only content is unavailable. Facebook Recommendations are not converted into star ratings.</p>{profile.error&&<div className="platform-access" role="status"><strong>Collection unavailable</strong><p>{profile.error}</p>{snapshot&&<p>The previous snapshot is retained below; it is not a fresh collection.</p>}</div>}{profile.lastAttemptAt&&<small>Last attempt: {new Date(profile.lastAttemptAt).toLocaleString()}</small>}
          {snapshot&&<div className="platform-evidence"><h3>{snapshot.name??label(platform)+" profile"}</h3><p>Collected {new Date(snapshot.collectedAt).toLocaleString()}</p><div className="platform-metrics"><div><span>Platform rating</span><strong>{snapshot.rating??"Unknown"}</strong></div><div><span>Reported reviews</span><strong>{snapshot.reviewCount?.toLocaleString()??"Unknown"}</strong></div><div><span>Texts collected</span><strong>{snapshot.reviews.length}</strong></div></div><p>Partial public sample. Missing reviews do not establish removals. These ratings are not combined with Google.</p><details><summary>Collected reviews ({snapshot.reviews.length})</summary>{snapshot.reviews.map(r=><article className="platform-review" key={r.id}><strong>{r.author??"Author unavailable"}</strong><small>{r.rating===null?"Rating unknown":`${r.rating} / 5`} · {r.postedAt?new Date(r.postedAt).toLocaleDateString():"Date unknown"}</small><p>{r.text}</p><details><summary>Report kit</summary><p>Open this {label(platform)} profile and locate the review by its author, date and text. Check the platform’s own rules before using its report menu. This panel does not establish a policy violation or submit a complaint.</p><a href={profile.url} target="_blank" rel="noreferrer">Open source profile</a><button className="text-button" onClick={()=>{const content=`${label(platform)} review locator\nBusiness: ${entity.name}\nSource: ${snapshot.sourceUrl}\nCollected: ${snapshot.collectedAt}\nAuthor: ${r.author??"Unknown"}\nPosted: ${r.postedAt??"Unknown"}\nRating: ${r.rating??"Unknown"}\nReview: ${r.text}\nSnapshot SHA-256: ${snapshot.digest}\n\nVerified policy reason: [complete after checking the source]\nSupporting evidence: [add references]\nManual submission required. No violation has been established by this export.`;const url=URL.createObjectURL(new Blob([content],{type:"text/plain"}));const a=document.createElement("a");a.href=url;a.download=`${platform}-review-${r.id.slice(0,12)}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Download review locator</button></details></article>)}</details><details><summary>Saved collection history ({profile.snapshots.length})</summary>{profile.snapshots.map(s=><p key={s.id}>{new Date(s.collectedAt).toLocaleString()} · {s.rating??"Unknown"} rating · {s.reviewCount??"Unknown"} reported reviews · {s.reviews.length} texts</p>)}</details></div>}
          <details className="platform-remove"><summary>Remove platform link</summary><p>This deletes this platform link and its saved preview snapshots.</p><button className="text-button" disabled={busy} onClick={()=>void unlink(profile)}>Remove {label(platform)} link and snapshots</button></details></>}
      </section>;})}</div><p className="platform-note">Google AI assessments and Google reporting cases remain specific to Google. Facebook and Trustpilot analysis, policy mapping and automated schedules are still planned.</p></>}
  </div>;
}
