import { useEffect, useState, useRef } from "react";
import { BrainCircuit, Download, LoaderCircle } from "lucide-react";
import type { CollectedListing } from "./intelligence-data";
import "./review-analysis.css";
import ReviewReportKit from "./ReviewReportKit";

export interface Finding {reviewRef:string;priority:string;policy:string;reasoning:string;alternativeExplanation:string;evidence:{reviewRef:string;quote:string}[];nextStep:string}
export interface Report {datasetId:string;listingId:string;id:string;summary:string;reviews:Finding[];model:string;provider?:"azure"|"openai";createdAt:string;collectedAt:string|null;analyzedCount:number;collectedCount:number;reportedCount:number|null;truncatedCount:number;batchSummaries?:string[];reviewIds:Record<string,string>;inputHash:string;usage:{inputTokens:number;outputTokens:number}}
interface Status {configured:boolean;provider?:"azure"|"openai";configurationError?:string|null;model:string;report:Report|null}
const policyUrl="https://support.google.com/contributionpolicy/answer/7400114?hl=en",reportUrl="https://support.google.com/contributionpolicy/answer/7445749";
const label=(s:string)=>s.replaceAll("_"," ");
export default function ReviewAnalysisPanel({datasetId,listing,collectedAt,onReport,showReviewKits=true}:{datasetId:string;listing:CollectedListing;collectedAt?:string|null;onReport?:(report:Report|null)=>void;showReviewKits?:boolean}){
  const [state,setState]=useState<Status|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const selection=useRef(0), stop=useRef(false);
  useEffect(()=>{const epoch=++selection.current;let active=true;setState(null);setError("");setBusy(false);void fetch(`/api/review-analysis?datasetId=${encodeURIComponent(datasetId)}&listingId=${encodeURIComponent(listing.id)}`).then(async response=>{const value=await response.json();if(!response.ok)throw new Error(value.error??"Analysis status unavailable.");if(active)setState(value);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;if(selection.current===epoch)selection.current++;};},[datasetId,listing.id]);
  async function analyze(){const epoch=selection.current;stop.current=false;setBusy(true);setError("");try{do{const response=await fetch("/api/review-analysis",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({datasetId,listingId:listing.id})});const value=await response.json();if(selection.current!==epoch)return;if(!response.ok)throw new Error(value.error??"Analysis failed.");setState(current=>({...current!,report:value}));if(value.analyzedCount>=value.collectedCount||stop.current)break;await new Promise(resolve=>setTimeout(resolve,1000));}while(selection.current===epoch&&!stop.current);}catch(e){if(selection.current===epoch)setError(e instanceof Error?e.message:"Analysis failed.");}finally{if(selection.current===epoch)setBusy(false);}}
  const report=state?.report;
  const provider=state?.provider==="azure"?"Azure OpenAI":"OpenAI";
  useEffect(()=>{onReport?.(report??null);},[report,onReport]);
  const source=(ref:string)=>listing.reviews.find(r=>r.id===report?.reviewIds[ref]);
  function download(){if(!report)return;const text=[`Axio-CRED investigation draft — ${listing.name}`,`Generated: ${report.createdAt} | Model: ${report.model}`,`Evidence collected: ${report.collectedAt??"unknown"}`,`Scope: ${report.analyzedCount} analyzed / ${report.collectedCount} collected / ${report.reportedCount??"unknown"} reported reviews.`,"AI triage is not proof of fake engagement or a calibrated probability. Review each observation before making a report.",`Listing: ${listing.mapsUrl??"not available"}`,`Input digest: ${report.inputHash}`,report.summary,...report.reviews.map(row=>[`${row.reviewRef}: ${source(row.reviewRef)?.author??"Reviewer"} | ${label(row.priority)} investigation priority`, `Review ID: ${report.reviewIds[row.reviewRef]}`,`Potential policy: ${label(row.policy)}`,`Observation: ${row.reasoning}`,`Alternative explanation: ${row.alternativeExplanation}`,...row.evidence.map(e=>`Quoted review ${e.reviewRef}: ${e.quote}`),`Next step: ${row.nextStep}`].join("\n")),"Reporting: open the business in Google Maps, locate the specific review, and use its three-dot menu > Report review. Choose the applicable reason only after verifying a policy violation. Keep your case reference. No report is sent by Axio-CRED.",`Google policy: ${policyUrl}`,`Reporting instructions: ${reportUrl}`].join("\n\n");const url=URL.createObjectURL(new Blob([text],{type:"text/plain;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="axiocred-review-investigation.txt";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <section className="review-ai" aria-label="AI review analysis"><header><div><span><BrainCircuit size={18}/>{provider.toUpperCase()} REVIEW ANALYSIS</span><h3>Which reviews need a closer look?</h3></div><button className="button" disabled={!state?.configured||busy||!listing.reviews.length||Boolean(report&&report.analyzedCount>=listing.reviews.length)} onClick={()=>void analyze()}>{busy?<><LoaderCircle size={15}/>Analyzing…</>:report?(report.analyzedCount>=listing.reviews.length?"Analysis saved":"Resume remaining reviews"):"Analyze collected reviews"}</button>{busy&&<button className="button secondary" onClick={()=>{stop.current=true;}}>Pause after this batch</button>}</header>
    <p>Investigation priorities, supporting quotes and alternative explanations. These are not measured probabilities of fakery. A small, selected sample cannot establish how many reviews are fake.</p>
    <div className="review-ai-scope"><strong>{report?.analyzedCount??0} / {listing.reviews.length}</strong> reviews assessed · {listing.reviews.length} collected · {listing.reviewCount??"unknown"} reported</div>
    {!state&&!error&&<p role="status">Checking analysis configuration…</p>}
    {state&&!state.configured&&<p className="review-ai-setup">{state.configurationError ?? <>OpenAI is not connected. Set <code>OPENAI_API_KEY</code> in the backend environment and restart the API. The key never belongs in frontend settings.</>}</p>}
    {state?.configured&&!report&&<small>Configuration present for {provider}. Runs on request using {state.model}. Processes all collected reviews in resumable batches of up to 30 review texts, ratings, dates and owner replies to {provider}; author names and profile URLs are omitted. Text can still contain personal details. Existing results are reused for the same input.</small>}
    {busy&&<p role="status">Review analysis is running. Each batch can take up to two minutes. Completed batches are saved; resume if quota interrupts the run.</p>}
    {error&&<p className="error-box" role="alert">{error}</p>}
    {report&&<><div className="review-ai-summary"><h4>Collected-sample assessment</h4>{(report.batchSummaries??[report.summary]).map((summary,i)=><p key={i}>{(report.batchSummaries?.length??0)>1&&<b>Batch {i+1}: </b>}{summary}</p>)}<small>{report.model} · {new Date(report.createdAt).toLocaleString()} · {report.usage.inputTokens+report.usage.outputTokens} tokens{report.truncatedCount?` · ${report.truncatedCount} long review records truncated`:""}</small><button className="text-button" onClick={download}><Download size={14}/>Download investigation report</button></div><div className="review-ai-findings">{report.reviews.map(row=><details key={row.reviewRef}><summary><span>{source(row.reviewRef)?.author??row.reviewRef}</span><strong className={`review-ai-priority ${row.priority}`}>{label(row.priority)}</strong></summary><p><b>Observation:</b> {row.reasoning}</p><p><b>Potential policy:</b> {label(row.policy)}</p>{row.evidence.map((e,i)=><blockquote key={i}>{e.quote}<small>Source review: {e.reviewRef}</small></blockquote>)}<p><b>Alternative explanation:</b> {row.alternativeExplanation}</p><p><b>Next step:</b> {row.nextStep}</p>{source(row.reviewRef)?.authorUrl&&<a href={source(row.reviewRef)!.authorUrl!} target="_blank" rel="noreferrer">Open reviewer profile to verify</a>}</details>)}</div></>}
    {showReviewKits&&listing.reviews.map(review=><article className="review-ai-summary" key={review.id}><strong>{review.author}</strong><small>{review.rating??"Unknown"} / 5 · {review.when??"Date not collected"}</small><p>{review.text??"No text collected."}</p><ReviewReportKit listing={listing} review={review} datasetId={datasetId} collectedAt={collectedAt} inputHash={report?.inputHash} finding={report?.reviews.find(row=>report.reviewIds[row.reviewRef]===review.id)}/></article>)}
    <details className="review-ai-reporting"><summary>How to report a review on Google Maps</summary><ol><li>Check the original review and corroborate a specific Google policy violation. Generic praise or a high rating alone is insufficient.</li><li>Open the business in Google Maps, go to Reviews, and find the exact review.</li><li>Use the review’s three-dot menu → Report review, then choose the applicable reason.</li><li>Save the review reference, screenshots, supporting evidence and your report status. Google decides whether to remove it.</li></ol><p><a href={policyUrl} target="_blank" rel="noreferrer">Google content policy</a> · <a href={reportUrl} target="_blank" rel="noreferrer">Google’s reporting instructions</a></p><small>Axio-CRED prepares an investigation draft. It does not submit complaints or promise removal.</small></details>
  </section>;
}
