import {useEffect,useState,type ReactNode} from "react";
import {NavLink,useLocation} from "react-router-dom";
import {Bell,Building2,FileText,LayoutDashboard,Menu,Radar,Search,Settings,ShieldCheck,X} from "lucide-react";
import {api,type Overview} from "./api";
import "./mission.css";
function JourneyNav(){const location=useLocation();const params=new URLSearchParams(location.search);const scope=location.pathname==="/businesses"?"owned":location.pathname==="/competitors"?"competitor":params.get("scope");if(!["/businesses","/competitors","/evidence","/alerts","/reports"].includes(location.pathname)||(!scope&&location.pathname!=="/reports"))return null;const routes=[[scope==="owned"?"/businesses":scope==="competitor"?"/competitors":"/overview",scope==="owned"?"My businesses":scope==="competitor"?"Competitor watchlist":"Workspace home"],[`/evidence?scope=${scope??"all"}`,"Review evidence"],[`/alerts?scope=${scope??"all"}`,"Alerts & changes"],[`/reports?scope=${scope??"all"}`,"Report queue"]];return <nav className="journey-nav" aria-label="Monitoring workflow">{routes.map(([to,label],i)=><NavLink key={to} to={to}><span>{i+1}</span>{label}</NavLink>)}<small>Evidence first. You decide what to report.</small></nav>;}
export default function WorkflowShell({children}:{children:ReactNode}){
 const location=useLocation();const [menu,setMenu]=useState(false),[usage,setUsage]=useState<Overview>();
 useEffect(()=>{setMenu(false)},[location.pathname,location.search]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==="Escape")setMenu(false)};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[]);
 useEffect(()=>{const refresh=()=>{void api.overview().then(setUsage).catch(()=>setUsage(undefined))};refresh();window.addEventListener("axiocred:refresh",refresh);return()=>window.removeEventListener("axiocred:refresh",refresh)},[]);
 const groups=[{label:"START HERE",items:[["/overview",LayoutDashboard,"Workspace home"]]},{label:"YOUR GOALS",items:[["/businesses",ShieldCheck,"Protect my business"],["/competitors",Radar,"Monitor competitors"]]},{label:"REVIEW & ACT",items:[["/alerts",Bell,"Alerts & changes"],["/reports",FileText,"Report queue"]]}] as const;
 const tools=[["/collections",Search,"Collect evidence"],["/evidence",Search,"Review library"],["/platforms",Building2,"Linked platforms"],["/enrichment",Search,"Contact enrichment"],["/settings",Settings,"Settings & billing"]] as const;
 return <div className="app-shell">{menu&&<button className="workflow-overlay" aria-label="Close navigation" onClick={()=>setMenu(false)}/>}<aside className={`sidebar workflow-sidebar ${menu?"is-open":""}`}><div className="brand"><span className="brand-mark">AX</span><span>Axio-CRED</span></div><nav aria-label="Workspace navigation">{groups.map(group=><div key={group.label}><div className="nav-group-label">{group.label}</div>{group.items.map(([to,Icon,label])=><NavLink key={to} to={to} aria-label={label} title={label}><Icon size={18}/><span>{label}</span></NavLink>)}</div>)}<details className="sidebar-tools" open={tools.some(([path])=>path===location.pathname)}><summary>Tools & settings</summary><div>{tools.map(([to,Icon,label])=><NavLink key={to} to={to} aria-label={label} title={label}><Icon size={18}/><span>{label}</span></NavLink>)}</div></details></nav><div className="sidebar-foot"><div className="plan-chip"><span>{usage?.plan??"Loading"} plan · preview</span><strong>{usage?`${usage.locationsUsed} of ${usage.locationsLimit??"unlimited"} monitored businesses`:"Loading usage"}</strong></div><div className="user"><span className="avatar">LP</span><span><strong>Local preview</strong><small>Single test workspace</small></span></div></div></aside><main><header className="topbar"><button className="icon-button workflow-menu-button" aria-label={menu?"Close workspace menu":"Open workspace menu"} aria-expanded={menu} onClick={()=>setMenu(v=>!v)}>{menu?<X size={20}/>:<Menu size={20}/>}</button><div><strong>Axio-CRED workspace</strong><span className="live">Local preview</span></div><NavLink to="/alerts" className="workflow-top-link"><Bell size={17}/>Alerts inbox</NavLink></header><div className="page"><JourneyNav/>{children}</div></main></div>;
}
